foxglove_bridge:
  ros__parameters:
    topic_whitelist:
      - "^/robot_status/.*$"
      - "^/robot/startup/plug$"
      - "^/robot/startup/groups_state$"
      - "^/robot/startup/game_time$"
      - "^/game_score$"
      - "^/score$"
      - "^/robot/startup/ideal_score$"
      - "^/sima_001/status$"
      - "^/sima_002/status$"
      - "^/sima_003/status$"
      - "^/sima_004/status$"
      - "^/sima_011/status$"
      - "^/sima_012/status$"
      - "^/sima_013/status$"
      - "^/sima_014/status$"
      - "^/sima_ninja_0/status$"
      - "^/sima_ninja_1/status$"
      - "^/robot/on_put$"
      - "^/tf$"
      - "^/tf_static$"
      - "^/map$"
      - "^/map_updates$"
      - "^/global_costmap/costmap$"
      - "^/global_costmap/costmap_updates$"
      - "^/local_costmap/costmap$"
      - "^/local_costmap/costmap_updates$"
      - "^/candidates$"
      - "^/waypoints$"
    service_whitelist:
      # - "^/robot/startup/ready_signal$"
      - "^/robot/startup/web_plan$"
    client_topic_whitelist:
      - "(?!)"
