version: '3'
services:
  Eurobo2024-Web:
    build: .
    image: scx/eurobot2024-web:latest
    container_name: eurobot-web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /home/share/data:/data
    environment:
      - FLASK_ENV=development
