teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 5

    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 1.0
      y: 1.0
    scale_linear_turbo:
      x: 1.2
      y: 1.2

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 5.0
    scale_angular_turbo:
      yaw: 6.0